version: '2.1'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  # mysql:
  #   image: debezium/example-mysql:${DEBEZIUM_VERSION}
  #   ports:
  #    - 3309:3306
  #   environment:
  #    - MYSQL_ROOT_PASSWORD=debezium
  #    - MYSQL_USER=mysqluser
  #    - MYSQL_PASSWORD=mysqlpw
  # mongodb:
  #   image: mongo:latest
  #   ports:
  #    - 27017:27017
  # connect_source:
  #   image: debezium/connect:${DEBEZIUM_VERSION}
  #   build:
  #     context: debezium-mongodb
  #   ports:
  #    - 8083:8083
  #   links:
  #    - kafka
  #    - mysql
  #   environment:
  #    - BOOTSTRAP_SERVERS=kafka:9092
  #    - GROUP_ID=1
  #    - CONFIG_STORAGE_TOPIC=my_source_connect_configs
  #    - OFFSET_STORAGE_TOPIC=my_source_connect_offsets
  # connect_sink:
  #   image: debezium/connect-mongodb:${DEBEZIUM_VERSION}
  #   build:
  #     context: debezium-mongodb
  #   ports:
  #    - 8084:8083
  #   links:
  #    - kafka
  #    - mongodb
  #   environment:
  #    - BOOTSTRAP_SERVERS=kafka:9092
  #    - GROUP_ID=2
  #    - CONFIG_STORAGE_TOPIC=my_sink_connect_configs
  #    - OFFSET_STORAGE_TOPIC=my_sink_connect_offsets
  #    - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
  #    - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
  connect:
    image: debezium/connect-jdbc-es:${DEBEZIUM_VERSION}
    build:
      context: debezium-jdbc-es
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      # - mysql
      # - postgres
      # - elastic
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
  aggregator:
    image: debezium/kstreams-aggregator:${DEBEZIUM_VERSION}
    build:
      context: poc-ddd-aggregates
    links:
     - kafka
    environment:
     - JAVA_MAIN_CLASS=io.debezium.examples.aggregation.StreamingAggregatesDDD
     - PARENT_TOPIC=kidssy-provider.public.oganizer_employee
     - CHILDREN_TOPIC=kidssy-provider.public.oganizer_location
     - BOOTSTRAP_SERVERS=kafka:9092
    # depends_on:
    #  - connect_source
    command: >
      /bin/bash -c "
        while ! curl -f -s -X GET http://222.254.34.158:8083/connectors/kidssy-provider-locatin-connector;
        do
          echo 'Waiting for source connector to be deployed';
          sleep 1;
        done;
        echo 'Source connector deployed!';
        /opt/poc-ddd-aggregates/run-aggregator.sh
      "
